name: dog-vision
channels:
  - apple
  - defaults
  - conda-forge
dependencies:
  - absl-py=1.3.0=py38hca03da5_0
  - aiohttp=3.8.3=py38h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.5.0=py38hca03da5_0
  - appnope=0.1.2=py38hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h1a28f6b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=py38hca03da5_0
  - attrs=22.1.0=py38hca03da5_0
  - babel=2.11.0=py38hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py38hca03da5_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_osxarm64_openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py38hca03da5_0
  - bottleneck=1.3.5=py38heec5a64_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py38h1a28f6b_1002
  - c-ares=1.18.1=h1a28f6b_0
  - ca-certificates=2022.10.11=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py38hca03da5_0
  - cffi=1.15.1=py38h80987f9_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py38hca03da5_0
  - comm=0.1.2=py38hca03da5_0
  - contourpy=1.0.5=py38h525c30c_0
  - cryptography=38.0.4=py38h834c97f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py38hc377ac9_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py38hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fftw=3.3.9=h1a28f6b_1
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - frozenlist=1.3.3=py38h80987f9_0
  - gettext=0.21.0=h826f4ad_0
  - giflib=5.2.1=h1a28f6b_0
  - glib=2.69.1=h514c7bf_2
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - grpcio=1.42.0=py38h95c9599_0
  - gst-plugins-base=1.14.1=hf0a386a_0
  - gstreamer=1.14.1=he09cfb7_0
  - h5py=3.6.0=py38h7fe8675_0
  - hdf5=1.12.1=h160e8cb_2
  - icu=68.1=hc377ac9_0
  - idna=3.4=py38hca03da5_0
  - importlib-metadata=4.11.3=py38hca03da5_0
  - ipykernel=6.19.2=py38h86d0a89_0
  - ipython=8.7.0=py38hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.1=py38hca03da5_1
  - jinja2=3.1.2=py38hca03da5_0
  - joblib=1.1.1=py38hca03da5_0
  - jpeg=9e=h1a28f6b_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.16.0=py38hca03da5_0
  - jupyter=1.0.0=py38hca03da5_8
  - jupyter_client=7.4.8=py38hca03da5_0
  - jupyter_console=6.4.4=py38hca03da5_0
  - jupyter_core=5.1.1=py38hca03da5_0
  - jupyter_server=1.23.4=py38hca03da5_0
  - jupyterlab=3.5.2=py38hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.16.5=py38hca03da5_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.4.4=py38h313beb8_0
  - krb5=1.19.2=h3b8d789_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.86.0=h0f1d93c_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.8=h1a28f6b_5
  - libedit=3.1.20221030=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.2=hca03da5_6
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h1a28f6b_2
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libllvm12=12.0.0=h12f7ac0_4
  - libnghttp2=1.46.0=h95c9599_0
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.37=hb8d0fd4_0
  - libpq=12.9=h65cfe13_3
  - libprotobuf=3.20.1=h98b2900_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=hf27765b_0
  - libtiff=4.5.0=h2fd578a_0
  - libwebp=1.2.4=h68602c7_0
  - libwebp-base=1.2.4=h1a28f6b_0
  - libxml2=2.9.14=h8c5e841_0
  - libxslt=1.1.35=h9833966_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lxml=4.9.1=py38h2fae87d_0
  - lz4-c=1.9.4=h313beb8_0
  - markdown=3.4.1=py38hca03da5_0
  - markupsafe=2.1.1=py38h1a28f6b_0
  - matplotlib=3.6.2=py38hca03da5_0
  - matplotlib-base=3.6.2=py38h8bbb115_0
  - matplotlib-inline=0.1.6=py38hca03da5_0
  - mistune=0.8.4=py38h1a28f6b_1000
  - multidict=6.0.2=py38h1a28f6b_0
  - munkres=1.1.4=py_0
  - nbclassic=0.4.8=py38hca03da5_0
  - nbclient=0.5.13=py38hca03da5_0
  - nbconvert=6.5.4=py38hca03da5_0
  - nbformat=5.7.0=py38hca03da5_0
  - ncurses=6.3=h1a28f6b_3
  - nest-asyncio=1.5.6=py38hca03da5_0
  - notebook=6.5.2=py38hca03da5_0
  - notebook-shim=0.2.2=py38hca03da5_0
  - nspr=4.33=hc377ac9_0
  - nss=3.74=h142855e_0
  - numexpr=2.8.4=py38h79ee842_0
  - numpy=1.22.3=py38h25ab29e_0
  - numpy-base=1.22.3=py38h974a1f5_0
  - oauthlib=3.2.1=py38hca03da5_0
  - openblas=0.3.21=openmp_hf78f355_3
  - openssl=1.1.1s=h1a28f6b_0
  - packaging=22.0=py38hca03da5_0
  - pandas=1.5.2=py38h78102c4_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=hc377ac9_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py38hf4a492f_1
  - pip=22.3.1=py38hca03da5_0
  - pkgutil-resolve-name=1.3.10=py38hca03da5_0
  - platformdirs=2.5.2=py38hca03da5_0
  - ply=3.11=py38hca03da5_0
  - prometheus_client=0.14.1=py38hca03da5_0
  - prompt-toolkit=3.0.36=py38hca03da5_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py38h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.4.0=py38hca03da5_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py38hca03da5_0
  - pyqt=5.15.7=py38hc377ac9_0
  - pyqt5-sip=12.11.0=py38hc377ac9_0
  - pyrsistent=0.18.0=py38h1a28f6b_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.15=hc0d8a6c_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py38hca03da5_0
  - pytz=2022.7=py38hca03da5_0
  - pyzmq=23.2.0=py38hc377ac9_0
  - qt-main=5.15.2=ha2d02b5_7
  - qt-webengine=5.15.9=h2903aaf_4
  - qtconsole=5.3.2=py38hca03da5_0
  - qtpy=2.2.0=py38hca03da5_0
  - qtwebkit=5.212=h0f11f3c_4
  - readline=8.2=h1a28f6b_0
  - requests=2.28.1=py38hca03da5_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-learn=1.1.3=py38hc377ac9_0
  - scipy=1.9.3=py38h9d039d2_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py38hca03da5_0
  - sip=6.6.2=py38hc377ac9_0
  - sniffio=1.2.0=py38hca03da5_1
  - soupsieve=2.3.2.post1=py38hca03da5_0
  - sqlite=3.40.1=h7a7dc30_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.9.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py38ha6e5c4f_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow-deps=2.9.0=0
  - terminado=0.17.1=py38hca03da5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tinycss2=1.2.1=py38hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py38hca03da5_0
  - tornado=6.2=py38h1a28f6b_0
  - traitlets=5.7.1=py38hca03da5_0
  - typing-extensions=4.4.0=py38hca03da5_0
  - typing_extensions=4.4.0=py38hca03da5_0
  - urllib3=1.26.13=py38hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38hca03da5_1
  - websocket-client=0.58.0=py38hca03da5_4
  - werkzeug=2.2.2=py38hca03da5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38hca03da5_0
  - xz=5.2.8=h80987f9_0
  - yarl=1.8.1=py38h1a28f6b_0
  - zeromq=4.3.4=hc377ac9_0
  - zipp=3.11.0=py38hca03da5_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.2=h8574219_0
  - pip:
      - astunparse==1.6.3
      - dill==0.3.6
      - dm-tree==0.1.8
      - etils==1.0.0
      - flatbuffers==1.12
      - gast==0.4.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.58.0
      - importlib-resources==5.10.2
      - keras==2.9.0
      - keras-preprocessing==1.1.2
      - libclang==15.0.6.1
      - opt-einsum==3.3.0
      - promise==2.3
      - protobuf==3.20.3
      - six==1.15.0
      - tensorflow-datasets==4.8.1
      - tensorflow-estimator==2.9.0
      - tensorflow-hub==0.12.0
      - tensorflow-macos==2.9.0
      - tensorflow-metadata==1.12.0
      - tensorflow-metal==0.5.0
      - termcolor==2.2.0
      - tqdm==4.64.1
      - wrapt==1.14.1
prefix: /Users/blazej.przybyszewski/miniforge3/envs/dog-vision
